### model
model_name_or_path: /mnt/workspace/Models/Qwen2.5-7B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: scripts/deepspeed/ds_z2_config.json

### dataset
dataset: ra_multi_turn_mamrp
template: qwen
cutoff_len: 4096
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: /mnt/workspace/checkpoints/ReMA/sft/multi_turn_mamrp/ra_7b_full
logging_steps: 1
save_strategy: "no"
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: mt-ra_7b_full

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
sequence_parallel_size: 1
packing: true 

# ### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: epoch
